[package]
name = "crossplane-types-upbound-gcp-logging"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }

[package.metadata.crossplane.provider]
name = "logging"
family = "gcp"
src-version = "1.14.0"
managed-resources = [
    "folderbucketconfigs",
    "folderexclusions",
    "foldersinks",
    "logviews",
    "metrics",
    "projectbucketconfigs",
    "projectexclusions",
    "projectsinks",
]

[lints]
workspace = true

[dependencies]
k8s-openapi = { workspace = true }
kube = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
typed-builder = { workspace = true }
