[package]
name = "crossplane-types-upbound-gcp-bigquery"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }

[package.metadata.crossplane.provider]
name = "bigquery"
family = "gcp"
src-version = "1.14.0"
managed-resources = [
    "analyticshubdataexchangeiammembers",
    "analyticshubdataexchanges",
    "analyticshublistings",
    "connections",
    "datasetaccesses",
    "datasetiambindings",
    "datasetiammembers",
    "datasetiampolicies",
    "datasets",
    "datatransferconfigs",
    "jobs",
    "reservationassignments",
    "reservations",
    "routines",
    "tableiambindings",
    "tableiammembers",
    "tableiampolicies",
    "tables",
]

[lints]
workspace = true

[dependencies]
k8s-openapi = { workspace = true }
kube = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
typed-builder = { workspace = true }
