#[cfg(feature = "aws-accessanalyzer")]
pub mod accessanalyzer;
#[cfg(feature = "aws-account")]
pub mod account;
#[cfg(feature = "aws-acm")]
pub mod acm;
#[cfg(feature = "aws-acmpca")]
pub mod acmpca;
#[cfg(feature = "aws-amp")]
pub mod amp;
#[cfg(feature = "aws-amplify")]
pub mod amplify;
#[cfg(feature = "aws-apigateway")]
pub mod apigateway;
#[cfg(feature = "aws-apigatewayv2")]
pub mod apigatewayv2;
#[cfg(feature = "aws-appautoscaling")]
pub mod appautoscaling;
#[cfg(feature = "aws-appconfig")]
pub mod appconfig;
#[cfg(feature = "aws-appflow")]
pub mod appflow;
#[cfg(feature = "aws-appintegrations")]
pub mod appintegrations;
#[cfg(feature = "aws-applicationinsights")]
pub mod applicationinsights;
#[cfg(feature = "aws-appmesh")]
pub mod appmesh;
#[cfg(feature = "aws-apprunner")]
pub mod apprunner;
#[cfg(feature = "aws-appstream")]
pub mod appstream;
#[cfg(feature = "aws-appsync")]
pub mod appsync;
#[cfg(feature = "aws-athena")]
pub mod athena;
#[cfg(feature = "aws-autoscaling")]
pub mod autoscaling;
#[cfg(feature = "aws-autoscalingplans")]
pub mod autoscalingplans;
#[cfg(feature = "aws-backup")]
pub mod backup;
#[cfg(feature = "aws-batch")]
pub mod batch;
#[cfg(feature = "aws-bedrock")]
pub mod bedrock;
#[cfg(feature = "aws-bedrockagent")]
pub mod bedrockagent;
#[cfg(feature = "aws-budgets")]
pub mod budgets;
#[cfg(feature = "aws-ce")]
pub mod ce;
#[cfg(feature = "aws-chime")]
pub mod chime;
#[cfg(feature = "aws-cloud9")]
pub mod cloud9;
#[cfg(feature = "aws-cloudcontrol")]
pub mod cloudcontrol;
#[cfg(feature = "aws-cloudformation")]
pub mod cloudformation;
#[cfg(feature = "aws-cloudfront")]
pub mod cloudfront;
#[cfg(feature = "aws-cloudsearch")]
pub mod cloudsearch;
#[cfg(feature = "aws-cloudtrail")]
pub mod cloudtrail;
#[cfg(feature = "aws-cloudwatch")]
pub mod cloudwatch;
#[cfg(feature = "aws-cloudwatchevents")]
pub mod cloudwatchevents;
#[cfg(feature = "aws-cloudwatchlogs")]
pub mod cloudwatchlogs;
#[cfg(feature = "aws-codeartifact")]
pub mod codeartifact;
#[cfg(feature = "aws-codecommit")]
pub mod codecommit;
#[cfg(feature = "aws-codeguruprofiler")]
pub mod codeguruprofiler;
#[cfg(feature = "aws-codepipeline")]
pub mod codepipeline;
#[cfg(feature = "aws-codestarconnections")]
pub mod codestarconnections;
#[cfg(feature = "aws-codestarnotifications")]
pub mod codestarnotifications;
#[cfg(feature = "aws-cognitoidentity")]
pub mod cognitoidentity;
#[cfg(feature = "aws-cognitoidp")]
pub mod cognitoidp;
#[cfg(feature = "aws-configservice")]
pub mod configservice;
#[cfg(feature = "aws-connect")]
pub mod connect;
#[cfg(feature = "aws-cur")]
pub mod cur;
#[cfg(feature = "aws-dataexchange")]
pub mod dataexchange;
#[cfg(feature = "aws-datapipeline")]
pub mod datapipeline;
#[cfg(feature = "aws-datasync")]
pub mod datasync;
#[cfg(feature = "aws-dax")]
pub mod dax;
#[cfg(feature = "aws-deploy")]
pub mod deploy;
#[cfg(feature = "aws-detective")]
pub mod detective;
#[cfg(feature = "aws-devicefarm")]
pub mod devicefarm;
#[cfg(feature = "aws-directconnect")]
pub mod directconnect;
#[cfg(feature = "aws-dlm")]
pub mod dlm;
#[cfg(feature = "aws-dms")]
pub mod dms;
#[cfg(feature = "aws-docdb")]
pub mod docdb;
#[cfg(feature = "aws-ds")]
pub mod ds;
#[cfg(feature = "aws-dynamodb")]
pub mod dynamodb;
#[cfg(feature = "aws-ec2")]
pub mod ec2;
#[cfg(feature = "aws-ecr")]
pub mod ecr;
#[cfg(feature = "aws-ecrpublic")]
pub mod ecrpublic;
#[cfg(feature = "aws-ecs")]
pub mod ecs;
#[cfg(feature = "aws-efs")]
pub mod efs;
#[cfg(feature = "aws-eks")]
pub mod eks;
#[cfg(feature = "aws-elasticache")]
pub mod elasticache;
#[cfg(feature = "aws-elasticbeanstalk")]
pub mod elasticbeanstalk;
#[cfg(feature = "aws-elasticsearch")]
pub mod elasticsearch;
#[cfg(feature = "aws-elastictranscoder")]
pub mod elastictranscoder;
#[cfg(feature = "aws-elb")]
pub mod elb;
#[cfg(feature = "aws-elbv2")]
pub mod elbv2;
#[cfg(feature = "aws-emr")]
pub mod emr;
#[cfg(feature = "aws-emrserverless")]
pub mod emrserverless;
#[cfg(feature = "aws-evidently")]
pub mod evidently;
#[cfg(feature = "aws-firehose")]
pub mod firehose;
#[cfg(feature = "aws-fis")]
pub mod fis;
#[cfg(feature = "aws-fsx")]
pub mod fsx;
#[cfg(feature = "aws-gamelift")]
pub mod gamelift;
#[cfg(feature = "aws-glacier")]
pub mod glacier;
#[cfg(feature = "aws-globalaccelerator")]
pub mod globalaccelerator;
#[cfg(feature = "aws-glue")]
pub mod glue;
#[cfg(feature = "aws-grafana")]
pub mod grafana;
#[cfg(feature = "aws-guardduty")]
pub mod guardduty;
#[cfg(feature = "aws-iam")]
pub mod iam;
#[cfg(feature = "aws-identitystore")]
pub mod identitystore;
#[cfg(feature = "aws-imagebuilder")]
pub mod imagebuilder;
#[cfg(feature = "aws-inspector")]
pub mod inspector;
#[cfg(feature = "aws-inspector2")]
pub mod inspector2;
#[cfg(feature = "aws-iot")]
pub mod iot;
#[cfg(feature = "aws-ivs")]
pub mod ivs;
#[cfg(feature = "aws-kafka")]
pub mod kafka;
#[cfg(feature = "aws-kafkaconnect")]
pub mod kafkaconnect;
#[cfg(feature = "aws-kendra")]
pub mod kendra;
#[cfg(feature = "aws-keyspaces")]
pub mod keyspaces;
#[cfg(feature = "aws-kinesis")]
pub mod kinesis;
#[cfg(feature = "aws-kinesisanalytics")]
pub mod kinesisanalytics;
#[cfg(feature = "aws-kinesisanalyticsv2")]
pub mod kinesisanalyticsv2;
#[cfg(feature = "aws-kinesisvideo")]
pub mod kinesisvideo;
#[cfg(feature = "aws-kms")]
pub mod kms;
#[cfg(feature = "aws-lakeformation")]
pub mod lakeformation;
#[cfg(feature = "aws-lambda")]
pub mod lambda;
#[cfg(feature = "aws-lexmodels")]
pub mod lexmodels;
#[cfg(feature = "aws-licensemanager")]
pub mod licensemanager;
#[cfg(feature = "aws-lightsail")]
pub mod lightsail;
#[cfg(feature = "aws-location")]
pub mod location;
#[cfg(feature = "aws-macie2")]
pub mod macie2;
#[cfg(feature = "aws-mediaconvert")]
pub mod mediaconvert;
#[cfg(feature = "aws-medialive")]
pub mod medialive;
#[cfg(feature = "aws-mediapackage")]
pub mod mediapackage;
#[cfg(feature = "aws-mediastore")]
pub mod mediastore;
#[cfg(feature = "aws-memorydb")]
pub mod memorydb;
#[cfg(feature = "aws-mq")]
pub mod mq;
#[cfg(feature = "aws-mwaa")]
pub mod mwaa;
#[cfg(feature = "aws-neptune")]
pub mod neptune;
#[cfg(feature = "aws-networkfirewall")]
pub mod networkfirewall;
#[cfg(feature = "aws-networkmanager")]
pub mod networkmanager;
#[cfg(feature = "aws-opensearch")]
pub mod opensearch;
#[cfg(feature = "aws-opensearchserverless")]
pub mod opensearchserverless;
#[cfg(feature = "aws-opsworks")]
pub mod opsworks;
#[cfg(feature = "aws-organizations")]
pub mod organizations;
#[cfg(feature = "aws-osis")]
pub mod osis;
#[cfg(feature = "aws-pinpoint")]
pub mod pinpoint;
#[cfg(feature = "aws-pipes")]
pub mod pipes;
#[cfg(feature = "aws-qldb")]
pub mod qldb;
#[cfg(feature = "aws-quicksight")]
pub mod quicksight;
#[cfg(feature = "aws-ram")]
pub mod ram;
#[cfg(feature = "aws-rds")]
pub mod rds;
#[cfg(feature = "aws-redshift")]
pub mod redshift;
#[cfg(feature = "aws-redshiftserverless")]
pub mod redshiftserverless;
#[cfg(feature = "aws-resourcegroups")]
pub mod resourcegroups;
#[cfg(feature = "aws-rolesanywhere")]
pub mod rolesanywhere;
#[cfg(feature = "aws-route53")]
pub mod route53;
#[cfg(feature = "aws-route53recoverycontrolconfig")]
pub mod route53recoverycontrolconfig;
#[cfg(feature = "aws-route53recoveryreadiness")]
pub mod route53recoveryreadiness;
#[cfg(feature = "aws-route53resolver")]
pub mod route53resolver;
#[cfg(feature = "aws-rum")]
pub mod rum;
#[cfg(feature = "aws-s3")]
pub mod s3;
#[cfg(feature = "aws-s3control")]
pub mod s3control;
#[cfg(feature = "aws-sagemaker")]
pub mod sagemaker;
#[cfg(feature = "aws-scheduler")]
pub mod scheduler;
#[cfg(feature = "aws-schemas")]
pub mod schemas;
#[cfg(feature = "aws-secretsmanager")]
pub mod secretsmanager;
#[cfg(feature = "aws-securityhub")]
pub mod securityhub;
#[cfg(feature = "aws-serverlessrepo")]
pub mod serverlessrepo;
#[cfg(feature = "aws-servicecatalog")]
pub mod servicecatalog;
#[cfg(feature = "aws-servicediscovery")]
pub mod servicediscovery;
#[cfg(feature = "aws-servicequotas")]
pub mod servicequotas;
#[cfg(feature = "aws-ses")]
pub mod ses;
#[cfg(feature = "aws-sesv2")]
pub mod sesv2;
#[cfg(feature = "aws-sfn")]
pub mod sfn;
#[cfg(feature = "aws-signer")]
pub mod signer;
#[cfg(feature = "aws-simpledb")]
pub mod simpledb;
#[cfg(feature = "aws-sns")]
pub mod sns;
#[cfg(feature = "aws-sqs")]
pub mod sqs;
#[cfg(feature = "aws-ssm")]
pub mod ssm;
#[cfg(feature = "aws-ssoadmin")]
pub mod ssoadmin;
#[cfg(feature = "aws-swf")]
pub mod swf;
#[cfg(feature = "aws-timestreamwrite")]
pub mod timestreamwrite;
#[cfg(feature = "aws-transcribe")]
pub mod transcribe;
#[cfg(feature = "aws-transfer")]
pub mod transfer;
#[cfg(feature = "aws-vpc")]
pub mod vpc;
#[cfg(feature = "aws-waf")]
pub mod waf;
#[cfg(feature = "aws-wafregional")]
pub mod wafregional;
#[cfg(feature = "aws-wafv2")]
pub mod wafv2;
#[cfg(feature = "aws-workspaces")]
pub mod workspaces;
#[cfg(feature = "aws-xray")]
pub mod xray;
