[package]
name = "crossplane-types-upbound-aws-route53recoveryreadiness"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }

[package.metadata.crossplane.provider]
name = "route53recoveryreadiness"
family = "aws"
src-version = "1.21.1"
managed-resources = [
    "cells",
    "readinesschecks",
    "recoverygroups",
    "resourcesets",
]

[lints]
workspace = true

[dependencies]
k8s-openapi = { workspace = true, features = ["schemars"] }
kube = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
typed-builder = { workspace = true }

[dev-dependencies]
k8s-openapi = { workspace = true, features = ["latest"] }
