// WARNING: automatically generated by `crossplane-types-generator (v0.0.1)` - manual changes will be overwritten

pub mod environments;
pub mod instanceiammembers;
pub mod instances;
pub mod runtimeiammembers;
pub mod runtimes;

pub use environments::*;
pub use instanceiammembers::*;
pub use instances::*;
pub use runtimeiammembers::*;
pub use runtimes::*;

pub const PROVIDER_NAME: &str = "notebooks";
pub const PROVIDER_FAMILY: &str = "gcp";
pub const PROVIDER_SRC_VERSION: &str = "1.14.0";
