// WARNING: automatically generated by `crossplane-types-generator (v0.0.1)` - manual changes will be overwritten

pub mod voiceconnectorgroups;
pub mod voiceconnectorloggings;
pub mod voiceconnectororiginations;
pub mod voiceconnectors;
pub mod voiceconnectorstreamings;
pub mod voiceconnectorterminationcredentials;
pub mod voiceconnectorterminations;

pub use voiceconnectorgroups::*;
pub use voiceconnectorloggings::*;
pub use voiceconnectororiginations::*;
pub use voiceconnectors::*;
pub use voiceconnectorstreamings::*;
pub use voiceconnectorterminationcredentials::*;
pub use voiceconnectorterminations::*;

pub const PROVIDER_NAME: &str = "chime";
pub const PROVIDER_FAMILY: &str = "aws";
pub const PROVIDER_SRC_VERSION: &str = "1.21.1";
