[package]
name = "crossplane-types-upbound-gcp-cloudplatform"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }

[package.metadata.crossplane.provider]
name = "cloudplatform"
family = "gcp"
src-version = "1.14.0"
managed-resources = [
    "folderiammembers",
    "folders",
    "organizationiamauditconfigs",
    "organizationiamcustomroles",
    "organizationiammembers",
    "projectdefaultserviceaccounts",
    "projectiamauditconfigs",
    "projectiamcustomroles",
    "projectiammembers",
    "projects",
    "projectservices",
    "projectusageexportbuckets",
    "serviceaccountiammembers",
    "serviceaccountkeys",
    "serviceaccounts",
    "servicenetworkingpeereddnsdomains",
]

[lints]
workspace = true

[dependencies]
k8s-openapi = { workspace = true }
kube = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
typed-builder = { workspace = true }
