// WARNING: automatically generated by `crossplane-types-generator (v0.0.1)` - manual changes will be overwritten

pub mod agentpools;

pub use agentpools::*;

pub const PROVIDER_NAME: &str = "storagetransfer";
pub const PROVIDER_FAMILY: &str = "gcp";
pub const PROVIDER_SRC_VERSION: &str = "1.14.0";
