[package]
name = "crossplane-types-upbound-aws-s3control"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }

[package.metadata.crossplane.provider]
name = "s3control"
family = "aws"
src-version = "1.21.1"
managed-resources = [
    "accesspointpolicies",
    "accesspoints",
    "accountpublicaccessblocks",
    "multiregionaccesspointpolicies",
    "multiregionaccesspoints",
    "objectlambdaaccesspointpolicies",
    "objectlambdaaccesspoints",
    "storagelensconfigurations",
]

[lints]
workspace = true

[dependencies]
k8s-openapi = { workspace = true }
kube = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
typed-builder = { workspace = true }
