[package]
name = "crossplane-types-upbound-aws-opsworks"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }

[package.metadata.crossplane.provider]
name = "opsworks"
family = "aws"
src-version = "1.21.1"
managed-resources = [
    "applications",
    "customlayers",
    "ecsclusterlayers",
    "ganglialayers",
    "haproxylayers",
    "instances",
    "javaapplayers",
    "memcachedlayers",
    "mysqllayers",
    "nodejsapplayers",
    "permissions",
    "phpapplayers",
    "railsapplayers",
    "rdsdbinstances",
    "stacks",
    "staticweblayers",
    "userprofiles",
]

[lints]
workspace = true

[dependencies]
k8s-openapi = { workspace = true, features = ["schemars"] }
kube = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
typed-builder = { workspace = true }

[dev-dependencies]
k8s-openapi = { workspace = true, features = ["latest"] }
