[package]
name = "crossplane-types-upbound-gcp-dialogflowcx"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }

[package.metadata.crossplane.provider]
name = "dialogflowcx"
family = "gcp"
src-version = "1.14.0"
managed-resources = [
    "agents",
    "entitytypes",
    "environments",
    "flows",
    "intents",
    "pages",
    "versions",
    "webhooks",
]

[lints]
workspace = true

[dependencies]
k8s-openapi = { workspace = true }
kube = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
typed-builder = { workspace = true }

[dev-dependencies]
k8s-openapi = { workspace = true, features = ["latest", "schemars"] }
