// WARNING: automatically generated by `crossplane-types-generator (v0.0.1)` - manual changes will be overwritten

pub mod bucketaccesscontrols;
pub mod bucketacls;
pub mod bucketiammembers;
pub mod bucketiampolicies;
pub mod bucketobjects;
pub mod buckets;
pub mod defaultobjectaccesscontrols;
pub mod defaultobjectacls;
pub mod hmackeys;
pub mod notifications;
pub mod objectaccesscontrols;
pub mod objectacls;

pub use bucketaccesscontrols::*;
pub use bucketacls::*;
pub use bucketiammembers::*;
pub use bucketiampolicies::*;
pub use bucketobjects::*;
pub use buckets::*;
pub use defaultobjectaccesscontrols::*;
pub use defaultobjectacls::*;
pub use hmackeys::*;
pub use notifications::*;
pub use objectaccesscontrols::*;
pub use objectacls::*;

pub const PROVIDER_NAME: &str = "storage";
pub const PROVIDER_FAMILY: &str = "gcp";
pub const PROVIDER_SRC_VERSION: &str = "1.14.0";
