// WARNING: automatically generated by `crossplane-types-generator (v0.0.1)` - manual changes will be overwritten

pub mod experimenttemplates;

pub use experimenttemplates::*;

pub const PROVIDER_NAME: &str = "fis";
pub const PROVIDER_FAMILY: &str = "aws";
pub const PROVIDER_SRC_VERSION: &str = "1.21.1";
