// WARNING: automatically generated by `crossplane-types-generator (v0.0.1)` - manual changes will be overwritten

pub mod platformapplications;
pub mod smspreferences;
pub mod topicpolicies;
pub mod topics;
pub mod topicsubscriptions;

pub use platformapplications::*;
pub use smspreferences::*;
pub use topicpolicies::*;
pub use topics::*;
pub use topicsubscriptions::*;

pub const PROVIDER_NAME: &str = "sns";
pub const PROVIDER_FAMILY: &str = "aws";
pub const PROVIDER_SRC_VERSION: &str = "1.21.1";
