// WARNING: automatically generated by `crossplane-types-generator (v0.0.1)` - manual changes will be overwritten

pub mod alertmanagerdefinitions;
pub mod rulegroupnamespaces;
pub mod workspaces;

pub use alertmanagerdefinitions::*;
pub use rulegroupnamespaces::*;
pub use workspaces::*;

pub const PROVIDER_NAME: &str = "amp";
pub const PROVIDER_FAMILY: &str = "aws";
pub const PROVIDER_SRC_VERSION: &str = "1.21.1";
