[package]
name = "crossplane-types-upbound-gcp-apigee"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }

[package.metadata.crossplane.provider]
name = "apigee"
family = "gcp"
src-version = "1.14.0"
managed-resources = [
    "addonsconfigs",
    "endpointattachments",
    "envgroupattachments",
    "envgroups",
    "environmentiammembers",
    "environments",
    "instanceattachments",
    "instances",
    "nataddresses",
    "organizations",
    "syncauthorizations",
]

[lints]
workspace = true

[dependencies]
k8s-openapi = { workspace = true }
kube = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
typed-builder = { workspace = true }

[dev-dependencies]
k8s-openapi = { workspace = true, features = ["latest", "schemars"] }
