[package]
name = "crossplane-types-upbound-gcp-alloydb"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }

[package.metadata.crossplane.provider]
name = "alloydb"
family = "gcp"
src-version = "1.14.0"
managed-resources = [
    "backups",
    "clusters",
    "instances",
]

[lints]
workspace = true

[dependencies]
k8s-openapi = { workspace = true, features = ["schemars"] }
kube = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
typed-builder = { workspace = true }

[dev-dependencies]
k8s-openapi = { workspace = true, features = ["latest"] }
